#!/usr/bin/env python

"""
	E-Minder 
	Setting email-based reminders via the command line
"""

import sys, datetime, logging
from utils import *
from configs import path_to_storage
from application_logger import *

# Creating a new reminder - getting and saving relevant user input
if len(sys.argv) == 1:
	# getting user input dependent on which Python version is being used
	try:
		if check_py_version(3):
			reminder = input("Reminder: \n")
			date = input("Date (19.01.19): \n")
		else:
			reminder = raw_input("Reminder: \n")
			date = raw_input("Date (e.g. 19.01.19): \n")

		# write reminder to storage
		save_reminder(reminder, date, path_to_storage)
	except Exception as e:
		logger.debug("Error: " + str(e))


# Sending off reminders that are due today
if len(sys.argv) > 1 and sys.argv[1] == "send_todays":
	try:
		# send_todays_reminders returns those reminders that are yet to be sent
		not_sent_yet = send_todays_reminders()

		# writing the reminders that are yet to be sent back to storage
		with open(path_to_storage, "w") as storage_f:
			for each in not_sent_yet:
				storage_f.write(each)
	except Exception as e:
		logger.debug("Error: " + str(e))


# write tests
# putting different files into different directories ...
# --> stickwort - directory organisaion of larger applications ...